[project]
name = "real-time-chat-application"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bcrypt>=4.2.0",
    "cryptography>=43.0.3",
    "flasgger>=0.9.7.1",
    "flet>=0.24.1",
]
